/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PageEntry } from "./Repository";
export { PageEntry } from "./Repository";
export namespace Components {
    interface XApp {
    }
    interface XButton {
        "href": string;
    }
    interface XGithubContributors {
    }
    interface XGithubLink {
    }
    interface XLogo {
        "size": number;
    }
    interface XNavbar {
    }
    interface XPage {
        "entry": PageEntry | null;
    }
    interface XSignature {
        "size": number;
    }
    interface XSitemap {
    }
}
declare global {
    interface HTMLXAppElement extends Components.XApp, HTMLStencilElement {
    }
    var HTMLXAppElement: {
        prototype: HTMLXAppElement;
        new (): HTMLXAppElement;
    };
    interface HTMLXButtonElement extends Components.XButton, HTMLStencilElement {
    }
    var HTMLXButtonElement: {
        prototype: HTMLXButtonElement;
        new (): HTMLXButtonElement;
    };
    interface HTMLXGithubContributorsElement extends Components.XGithubContributors, HTMLStencilElement {
    }
    var HTMLXGithubContributorsElement: {
        prototype: HTMLXGithubContributorsElement;
        new (): HTMLXGithubContributorsElement;
    };
    interface HTMLXGithubLinkElement extends Components.XGithubLink, HTMLStencilElement {
    }
    var HTMLXGithubLinkElement: {
        prototype: HTMLXGithubLinkElement;
        new (): HTMLXGithubLinkElement;
    };
    interface HTMLXLogoElement extends Components.XLogo, HTMLStencilElement {
    }
    var HTMLXLogoElement: {
        prototype: HTMLXLogoElement;
        new (): HTMLXLogoElement;
    };
    interface HTMLXNavbarElement extends Components.XNavbar, HTMLStencilElement {
    }
    var HTMLXNavbarElement: {
        prototype: HTMLXNavbarElement;
        new (): HTMLXNavbarElement;
    };
    interface HTMLXPageElement extends Components.XPage, HTMLStencilElement {
    }
    var HTMLXPageElement: {
        prototype: HTMLXPageElement;
        new (): HTMLXPageElement;
    };
    interface HTMLXSignatureElement extends Components.XSignature, HTMLStencilElement {
    }
    var HTMLXSignatureElement: {
        prototype: HTMLXSignatureElement;
        new (): HTMLXSignatureElement;
    };
    interface HTMLXSitemapElement extends Components.XSitemap, HTMLStencilElement {
    }
    var HTMLXSitemapElement: {
        prototype: HTMLXSitemapElement;
        new (): HTMLXSitemapElement;
    };
    interface HTMLElementTagNameMap {
        "x-app": HTMLXAppElement;
        "x-button": HTMLXButtonElement;
        "x-github-contributors": HTMLXGithubContributorsElement;
        "x-github-link": HTMLXGithubLinkElement;
        "x-logo": HTMLXLogoElement;
        "x-navbar": HTMLXNavbarElement;
        "x-page": HTMLXPageElement;
        "x-signature": HTMLXSignatureElement;
        "x-sitemap": HTMLXSitemapElement;
    }
}
declare namespace LocalJSX {
    interface XApp {
    }
    interface XButton {
        "href"?: string;
    }
    interface XGithubContributors {
    }
    interface XGithubLink {
    }
    interface XLogo {
        "size"?: number;
    }
    interface XNavbar {
    }
    interface XPage {
        "entry"?: PageEntry | null;
    }
    interface XSignature {
        "size"?: number;
    }
    interface XSitemap {
    }
    interface IntrinsicElements {
        "x-app": XApp;
        "x-button": XButton;
        "x-github-contributors": XGithubContributors;
        "x-github-link": XGithubLink;
        "x-logo": XLogo;
        "x-navbar": XNavbar;
        "x-page": XPage;
        "x-signature": XSignature;
        "x-sitemap": XSitemap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-app": LocalJSX.XApp & JSXBase.HTMLAttributes<HTMLXAppElement>;
            "x-button": LocalJSX.XButton & JSXBase.HTMLAttributes<HTMLXButtonElement>;
            "x-github-contributors": LocalJSX.XGithubContributors & JSXBase.HTMLAttributes<HTMLXGithubContributorsElement>;
            "x-github-link": LocalJSX.XGithubLink & JSXBase.HTMLAttributes<HTMLXGithubLinkElement>;
            "x-logo": LocalJSX.XLogo & JSXBase.HTMLAttributes<HTMLXLogoElement>;
            "x-navbar": LocalJSX.XNavbar & JSXBase.HTMLAttributes<HTMLXNavbarElement>;
            "x-page": LocalJSX.XPage & JSXBase.HTMLAttributes<HTMLXPageElement>;
            "x-signature": LocalJSX.XSignature & JSXBase.HTMLAttributes<HTMLXSignatureElement>;
            "x-sitemap": LocalJSX.XSitemap & JSXBase.HTMLAttributes<HTMLXSitemapElement>;
        }
    }
}
